language: r
warnings_are_errors: false
install:
- Rscript Installations.R
before_install:
- openssl aes-256-cbc -K $encrypted_48435adfb8bd_key -iv $encrypted_48435adfb8bd_iv
  -in tests/testthat/.httr-oauth.enc -out tests/testthat/.httr-oauth -d
