language: r
warnings_are_errors: false
install:
- Rscript Installations.R
before_install:
- openssl aes-256-cbc -K $encrypted_e47b7026c705_key -iv $encrypted_e47b7026c705_iv
  -in tests/testthat/secrets.tar.enc -out tests/testthat/secrets.tar -d
- tar xvf tests/testthat/secrets.tar
- mv tests/testthat/.Renviron .Renviron
- cat .Renviron