language: r
warnings_are_errors: false
install:
- Rscript Installations.R
dd:
- openssl aes-256-cbc -K $encrypted_e47b7026c705_key -iv $encrypted_e47b7026c705_iv
  -in secrets.tar.enc -out tests/testthat/secrets.tar -d
